### ISSUE TITLE
remove font awesome dep replace with google material icons

### ISSUE THREAD

**Issue by wafis** [jyoung295/palettify#1]
https://fonts.google.com/icons

reduces bundle size by removing these dependencies 

``` 
"@fortawesome/fontawesome-svg-core": "^1.2.35",

 "@fortawesome/free-solid-svg-icons": "^5.15.3",

 "@fortawesome/react-fontawesome": "^0.1.14",
```

simply import the style sheet in the head of your index.html and slap 
```
class="material-icons"
```
 in your _i_ tags

**Comment by jyoung295** [comment]
This is the move for sure.

**Comment by jyoung295** [comment]
Done in c33f592
